### ISSUE TITLE
clock branding issue

### ISSUE THREAD

**Issue by valbuilds** [playsamay4/Viz2.0#2]
even though i have the clock setting to "off", the clock still shows

**Comment by RealJoBoGamer** [comment]
> even though i have the clock setting to "off", the clock still shows

Make sure you click send in the branding options.
![image](https://github.com/playsamay4/Viz2.0/assets/78912075/2705cf58-13ee-4041-bc58-dfd60dd9998d)

**Comment by valbuilds** [comment]
@RealJoBoGamer I have tried, that yet I'm still running into issues with the clock.

**Comment by RealJoBoGamer** [comment]
> @RealJoBoGamer I have tried, that yet I'm still running into issues with the clock.

could you share an image or video of what happens?

**Comment by valbuilds** [comment]
i figured out my issue, its because im not renaming my presets :idiot:
